/**
 * GENERATED by packages/runink-ui/scripts/gen-tokens.mjs from DESIGN.md.
 * Do not edit by hand — edit DESIGN.md and re-run `npm run gen:tokens`
 * from packages/runink-ui.
 *
 * Shared Tailwind preset: the single source of truth for Runink's design tokens.
 * Consumed by site/tailwind.config.js (the Hugo site) and by @runink/ui (the
 * React component library that claude.ai/design builds with), so both render
 * the same brand.
 *
 * Only tokens that DIFFER from Tailwind's stock theme live here. DESIGN.md's
 * type scale, spacing scale and motion durations are identical to Tailwind's
 * defaults and are deliberately not re-emitted.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  theme: {
    extend: {
      "colors": {
        "primary": {
          "50": "#eef1fc",
          "100": "#dde3f9",
          "200": "#bbc7f3",
          "300": "#99abec",
          "400": "#778fe6",
          "500": "#5573df",
          "600": "#425ad6",
          "700": "#3548ab",
          "800": "#283680",
          "900": "#1b2456",
          "950": "#0f1330"
        },
        "secondary": {
          "50": "#faf5ff",
          "100": "#f3e8ff",
          "200": "#e9d5ff",
          "300": "#d8b4fe",
          "400": "#c084fc",
          "500": "#a855f7",
          "600": "#9333ea",
          "700": "#7e22ce",
          "800": "#6b21a8",
          "900": "#581c87"
        },
        "brand": {
          "orange": "#ea580c",
          "orange-dark": "#ca4708",
          "green": "#65793e",
          "green-dark": "#5F6F3E",
          "red": "#991b1b",
          "sage": "#C8D9A8",
          "tan": "#D4A574",
          "ink": "#161515",
          "ink-soft": "#1b1919",
          "ink-raised": "#211F1F",
          "green-deep": "#526332",
          "sage-dark": "#A8B88B",
          "copper": "#B87333",
          "paper": "#F5F1E8",
          "beige": "#D9CDB8"
        }
      },
      "fontFamily": {
        "sans": [
          "Inter",
          "system-ui",
          "sans-serif"
        ],
        "heading": [
          "Plus Jakarta Sans",
          "sans-serif"
        ],
        "mono": [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace"
        ]
      },
      "borderRadius": {
        "card": "2rem",
        "large": "2.5rem"
      },
      "boxShadow": {
        "neon-orange": "0 0 15px rgba(234, 88, 12, 0.1)",
        "neon-green": "0 0 15px rgba(101, 121, 62, 0.3)",
        "neon-orange-strong": "0 0 25px rgba(234, 88, 12, 0.3)",
        "neon-red": "0 0 15px rgba(153, 27, 27, 0.3)"
      },
      "keyframes": {
        "cta-pulse": {
          "0%": {
            "boxShadow": "0 0 0 0 rgba(234, 88, 12, 0.4)"
          },
          "70%": {
            "boxShadow": "0 0 0 15px rgba(234, 88, 12, 0)"
          },
          "100%": {
            "boxShadow": "0 0 0 0 rgba(234, 88, 12, 0)"
          }
        },
        "marquee": {
          "from": {
            "transform": "translateX(0)"
          },
          "to": {
            "transform": "translateX(calc(-100% / 2))"
          }
        },
        "testimonials-scroll": {
          "from": {
            "transform": "translateX(0)"
          },
          "to": {
            "transform": "translateX(calc(-100% / 2))"
          }
        },
        "pulse-slow": {
          "0%, 100%": {
            "opacity": "1"
          },
          "50%": {
            "opacity": "0.4"
          }
        }
      },
      "animation": {
        "cta-pulse": "cta-pulse 2s infinite",
        "marquee": "marquee 40s infinite linear",
        "testimonials-scroll": "testimonials-scroll 40s infinite linear",
        "pulse-slow": "pulse-slow 4s cubic-bezier(0.4, 0, 0.6, 1) infinite"
      }
    },
  },
};
