/**
 * GENERATED by packages/runink-ui/scripts/gen-tokens.mjs — do not edit by hand.
 * Edit tokens/registry.json (the mapping) or tokens/derived.json (web-only values)
 * and re-run `npm run gen:tokens` from packages/runink-ui.
 *
 * Runink's palette, from FACE fef45f6ccdc1.
 *
 * Colour palettes are defined PER POSITION rather than once under `colors`. That is
 * what makes fill-vs-ink structural instead of a convention: a fill token has no
 * textColor entry, so `text-fill-success` does not compile. FACE enforces the same
 * rule with a contrast test suite; here the utility simply does not exist.
 *
 * Values are rgb(var(--…-ch) / <alpha-value>) so Tailwind's /NN modifier keeps
 * working across both grounds. See tokens.css for why channels rather than hexes.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  theme: {
    extend: {
      "backgroundColor": {
        "canvas": "rgb(var(--rk-canvas-ch) / <alpha-value>)",
        "surface": "rgb(var(--rk-surface-ch) / <alpha-value>)",
        "surface-raised": "rgb(var(--rk-surface-raised-ch) / <alpha-value>)",
        "surface-well": "rgb(var(--rk-surface-well-ch) / <alpha-value>)",
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)",
        "fill-accent-wash": "rgb(var(--rk-fill-accent-ch) / 0.15)",
        "fill-accent-deep": "rgb(var(--rk-fill-accent-deep-ch) / <alpha-value>)",
        "fill-accent-deep-wash": "rgb(var(--rk-fill-accent-deep-ch) / 0.15)",
        "fill-success": "rgb(var(--rk-fill-success-ch) / <alpha-value>)",
        "fill-success-wash": "rgb(var(--rk-fill-success-ch) / 0.15)",
        "fill-success-glow": "rgb(var(--rk-fill-success-glow-ch) / <alpha-value>)",
        "fill-provenance": "rgb(var(--rk-fill-provenance-ch) / <alpha-value>)",
        "fill-provenance-wash": "rgb(var(--rk-fill-provenance-ch) / 0.15)",
        "fill-severity": "rgb(var(--rk-fill-severity-ch) / <alpha-value>)"
      },
      "textColor": {
        "primary": "rgb(var(--rk-primary-ch) / <alpha-value>)",
        "secondary": "rgb(var(--rk-secondary-ch) / var(--rk-secondary-a))",
        "ink-accent": "rgb(var(--rk-ink-accent-ch) / <alpha-value>)",
        "ink-success": "rgb(var(--rk-ink-success-ch) / <alpha-value>)",
        "ink-provenance": "rgb(var(--rk-ink-provenance-ch) / <alpha-value>)",
        "ink-ice": "rgb(var(--rk-ink-ice-ch) / <alpha-value>)",
        "ink-violet": "rgb(var(--rk-ink-violet-ch) / <alpha-value>)",
        "on-accent": "rgb(var(--rk-on-accent-ch) / <alpha-value>)",
        "on-success": "rgb(var(--rk-on-success-ch) / <alpha-value>)",
        "on-provenance": "rgb(var(--rk-on-provenance-ch) / <alpha-value>)",
        "ink-severity-critical": "rgb(var(--rk-ink-severity-critical-ch) / <alpha-value>)",
        "ink-severity-high": "rgb(var(--rk-ink-severity-high-ch) / <alpha-value>)",
        "ink-severity-medium": "rgb(var(--rk-ink-severity-medium-ch) / <alpha-value>)",
        "ink-severity-low": "rgb(var(--rk-ink-severity-low-ch) / <alpha-value>)",
        "ink-severity-ok": "rgb(var(--rk-ink-severity-ok-ch) / <alpha-value>)"
      },
      "borderColor": {
        "hairline": "rgb(var(--rk-hairline-ch) / <alpha-value>)",
        "edge": "rgb(var(--rk-edge-ch) / var(--rk-edge-a))",
        "primary": "rgb(var(--rk-primary-ch) / <alpha-value>)",
        "ink-accent": "rgb(var(--rk-ink-accent-ch) / <alpha-value>)",
        "ink-success": "rgb(var(--rk-ink-success-ch) / <alpha-value>)",
        "ink-provenance": "rgb(var(--rk-ink-provenance-ch) / <alpha-value>)",
        "ink-ice": "rgb(var(--rk-ink-ice-ch) / <alpha-value>)",
        "ink-violet": "rgb(var(--rk-ink-violet-ch) / <alpha-value>)",
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)"
      },
      "divideColor": {
        "hairline": "rgb(var(--rk-hairline-ch) / <alpha-value>)",
        "edge": "rgb(var(--rk-edge-ch) / var(--rk-edge-a))"
      },
      "ringColor": {
        "edge": "rgb(var(--rk-edge-ch) / var(--rk-edge-a))",
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)"
      },
      "outlineColor": {
        "hairline": "rgb(var(--rk-hairline-ch) / <alpha-value>)",
        "edge": "rgb(var(--rk-edge-ch) / var(--rk-edge-a))",
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)"
      },
      "fill": {
        "primary": "rgb(var(--rk-primary-ch) / <alpha-value>)",
        "ink-accent": "rgb(var(--rk-ink-accent-ch) / <alpha-value>)",
        "ink-success": "rgb(var(--rk-ink-success-ch) / <alpha-value>)",
        "ink-provenance": "rgb(var(--rk-ink-provenance-ch) / <alpha-value>)",
        "ink-ice": "rgb(var(--rk-ink-ice-ch) / <alpha-value>)",
        "ink-violet": "rgb(var(--rk-ink-violet-ch) / <alpha-value>)",
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)",
        "on-accent": "rgb(var(--rk-on-accent-ch) / <alpha-value>)",
        "on-success": "rgb(var(--rk-on-success-ch) / <alpha-value>)",
        "on-provenance": "rgb(var(--rk-on-provenance-ch) / <alpha-value>)",
        "ink-severity-critical": "rgb(var(--rk-ink-severity-critical-ch) / <alpha-value>)",
        "ink-severity-high": "rgb(var(--rk-ink-severity-high-ch) / <alpha-value>)",
        "ink-severity-medium": "rgb(var(--rk-ink-severity-medium-ch) / <alpha-value>)",
        "ink-severity-low": "rgb(var(--rk-ink-severity-low-ch) / <alpha-value>)",
        "ink-severity-ok": "rgb(var(--rk-ink-severity-ok-ch) / <alpha-value>)"
      },
      "stroke": {
        "primary": "rgb(var(--rk-primary-ch) / <alpha-value>)",
        "ink-accent": "rgb(var(--rk-ink-accent-ch) / <alpha-value>)",
        "ink-success": "rgb(var(--rk-ink-success-ch) / <alpha-value>)",
        "ink-provenance": "rgb(var(--rk-ink-provenance-ch) / <alpha-value>)",
        "ink-ice": "rgb(var(--rk-ink-ice-ch) / <alpha-value>)",
        "ink-violet": "rgb(var(--rk-ink-violet-ch) / <alpha-value>)",
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)",
        "ink-severity-critical": "rgb(var(--rk-ink-severity-critical-ch) / <alpha-value>)",
        "ink-severity-high": "rgb(var(--rk-ink-severity-high-ch) / <alpha-value>)",
        "ink-severity-medium": "rgb(var(--rk-ink-severity-medium-ch) / <alpha-value>)",
        "ink-severity-low": "rgb(var(--rk-ink-severity-low-ch) / <alpha-value>)",
        "ink-severity-ok": "rgb(var(--rk-ink-severity-ok-ch) / <alpha-value>)"
      },
      "gradientColorStops": {
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)",
        "fill-accent-deep": "rgb(var(--rk-fill-accent-deep-ch) / <alpha-value>)",
        "accent-lift": "rgb(var(--rk-accent-lift-ch) / <alpha-value>)",
        "fill-success": "rgb(var(--rk-fill-success-ch) / <alpha-value>)",
        "fill-success-glow": "rgb(var(--rk-fill-success-glow-ch) / <alpha-value>)",
        "fill-provenance": "rgb(var(--rk-fill-provenance-ch) / <alpha-value>)"
      },
      "boxShadowColor": {
        "fill-accent": "rgb(var(--rk-fill-accent-ch) / <alpha-value>)",
        "fill-accent-deep": "rgb(var(--rk-fill-accent-deep-ch) / <alpha-value>)",
        "fill-success": "rgb(var(--rk-fill-success-ch) / <alpha-value>)",
        "fill-success-glow": "rgb(var(--rk-fill-success-glow-ch) / <alpha-value>)",
        "fill-provenance": "rgb(var(--rk-fill-provenance-ch) / <alpha-value>)"
      },
      "caretColor": {
        "primary": "rgb(var(--rk-primary-ch) / <alpha-value>)"
      },
      "textDecorationColor": {
        "primary": "rgb(var(--rk-primary-ch) / <alpha-value>)"
      },
      "borderRadius": {
        "badge": "6px",
        "chip": "12px",
        "card": "18px",
        "pill": "24px"
      },
      "boxShadow": {
        "glow-success": "0 0 24px 2px rgb(var(--rk-fill-success-ch) / 0.30)",
        "glow-accent": "0 0 24px 2px rgb(var(--rk-fill-accent-ch) / 0.30)"
      },
      "fontFamily": {
        "sans": [
          "Figtree Rk",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "sans-serif"
        ],
        "display": [
          "Figtree Rk",
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace"
        ]
      },
      "keyframes": {
        "cta-pulse": {
          "0%": {
            "boxShadow": "0 0 0 0 rgb(var(--rk-fill-accent-ch) / 0.4)"
          },
          "70%": {
            "boxShadow": "0 0 0 15px rgb(var(--rk-fill-accent-ch) / 0)"
          },
          "100%": {
            "boxShadow": "0 0 0 0 rgb(var(--rk-fill-accent-ch) / 0)"
          }
        },
        "marquee": {
          "from": {
            "transform": "translateX(0)"
          },
          "to": {
            "transform": "translateX(calc(-100% / 2))"
          }
        },
        "testimonials-scroll": {
          "from": {
            "transform": "translateX(0)"
          },
          "to": {
            "transform": "translateX(calc(-100% / 2))"
          }
        },
        "pulse-slow": {
          "0%, 100%": {
            "opacity": "1"
          },
          "50%": {
            "opacity": "0.4"
          }
        }
      },
      "animation": {
        "cta-pulse": "cta-pulse 2s infinite",
        "marquee": "marquee 40s infinite linear",
        "testimonials-scroll": "testimonials-scroll 40s infinite linear",
        "pulse-slow": "pulse-slow 4s cubic-bezier(0.4, 0, 0.6, 1) infinite"
      }
    },
  },
};
