import re

app_js_path = "/home/me/Documents/companion/demo/app.js"

with open(app_js_path, "r") as f:
    content = f.read()

new_schemas = """        const schemas3PL = {
          "Vehicle_State": "Columns:\\n- vehicle_id VARCHAR(36) (PK)\\n- geom_location GEOMETRY(Point, 4326)\\n- heading DECIMAL(5,2)\\n- velocity_kmh INT\\n- altitude_m DECIMAL(6,2)\\n- gps_status VARCHAR(16)\\n- ignition_status BOOLEAN\\n- fuel_level_pct DECIMAL(5,2)\\n- def_fluid_pct DECIMAL(5,2)\\n- engine_hours INT\\n- battery_volts DECIMAL(4,1)\\n- weight_on_axles JSONB\\n- dtc_fault_codes JSONB\\n- driver_id VARCHAR(64)\\n- obd2_vin VARCHAR(17)\\n- cell_signal_dbm INT\\n- firmware_version VARCHAR(32)\\n- _raw_nmea_payload JSONB\\n- _sync_hash VARCHAR(64)\\n- _kafka_offset BIGINT\\n- sys_created_on TIMESTAMP\\n- sys_updated_on TIMESTAMP\\n- is_active BOOLEAN",
          "GPS_Stream": "Columns:\\n- stream_id BIGINT (PK)\\n- raw_nmea_sentence TEXT\\n- parsed_lat DECIMAL(9,6)\\n- parsed_long DECIMAL(9,6)\\n- sat_count INT\\n- hdop FLOAT\\n- vdop FLOAT\\n- pdop FLOAT\\n- speed_knots DECIMAL(6,2)\\n- course_true DECIMAL(5,2)\\n- magnetic_variation DECIMAL(5,2)\\n- fix_quality INT\\n- dgps_age FLOAT\\n- dgps_station_id INT\\n- checksum VARCHAR(4)\\n- device_imei VARCHAR(32)\\n- ingested_at TIMESTAMP",
          "Engine_Metrics": "Columns:\\n- obd2_record_id UUID (PK)\\n- vehicle_id VARCHAR(36)\\n- rpm INT\\n- engine_load FLOAT\\n- coolant_temp INT\\n- dtc_codes JSONB\\n- intake_air_temp INT\\n- run_time INT\\n- mass_air_flow DECIMAL(6,2)\\n- throttle_pos DECIMAL(5,2)\\n- fuel_pressure DECIMAL(6,2)\\n- manifold_pressure INT\\n- timing_advance DECIMAL(5,2)\\n- o2_sensor_volts JSONB\\n- mil_distance INT\\n- egr_error DECIMAL(5,2)\\n- dpf_temp DECIMAL(6,2)\\n- dpf_diff_pressure DECIMAL(6,2)\\n- _raw_canbus_frame VARCHAR(128)\\n- recorded_at TIMESTAMP",
          "Zone_Temp": "Columns:\\n- sensor_id VARCHAR(50) (PK)\\n- recorded_at TIMESTAMP (PK)\\n- facility_id VARCHAR(32)\\n- zone_name VARCHAR(64)\\n- temperature_c DECIMAL(4,2)\\n- temperature_f DECIMAL(4,2)\\n- humidity_pct DECIMAL(4,2)\\n- dew_point_c DECIMAL(4,2)\\n- ambient_light_lux INT\\n- motion_detected BOOLEAN\\n- battery_level_pct INT\\n- voltage DECIMAL(4,2)\\n- signal_strength_dbm INT\\n- gateway_id VARCHAR(32)\\n- firmware_version VARCHAR(16)\\n- alert_flag BOOLEAN\\n- threshold_breach_type VARCHAR(16)\\n- _raw_lorawan_payload TEXT\\n- _message_seq INT\\n- sys_ingested_at TIMESTAMP",
          "Pallet_RFID": "Columns:\\n- epc_code VARCHAR(64) (PK)\\n- event_id UUID\\n- tag_type VARCHAR(16)\\n- read_timestamp TIMESTAMP\\n- reader_id VARCHAR(32)\\n- antenna_id VARCHAR(16)\\n- facility_code VARCHAR(16)\\n- zone_id VARCHAR(32)\\n- rssi_dbm FLOAT\\n- tx_power_dbm FLOAT\\n- peak_rssi FLOAT\\n- read_count INT\\n- phase_angle FLOAT\\n- doppler_shift FLOAT\\n- direction_vector VARCHAR(16)\\n- operator_id VARCHAR(32)\\n- pallet_type VARCHAR(16)\\n- contents_sku VARCHAR(64)\\n- _raw_hl7_packet JSONB\\n- _confidence_score FLOAT\\n- is_deleted BOOLEAN\\n- sys_updated_on TIMESTAMP",
          "Humidity_Log": "Columns:\\n- log_id BIGINT (PK)\\n- device_serial VARCHAR(32)\\n- relative_humidity FLOAT\\n- absolute_humidity FLOAT\\n- temp_ambient FLOAT\\n- dew_point FLOAT\\n- vapor_pressure FLOAT\\n- sensor_calibration_date DATE\\n- reading_interval_sec INT\\n- sync_status VARCHAR(16)\\n- battery_mv INT\\n- recorded_at TIMESTAMP",
          "Route_Plan": "Columns:\\n- route_id VARCHAR(36) (PK)\\n- vehicle_id VARCHAR(36)\\n- driver_id VARCHAR(64)\\n- start_node_id VARCHAR(36)\\n- end_node_id VARCHAR(36)\\n- planned_start TIMESTAMP\\n- planned_end TIMESTAMP\\n- waypoints JSONB\\n- segment_details JSONB\\n- estimated_distance_km DECIMAL(8,2)\\n- estimated_duration_sec INT\\n- total_tolls_usd DECIMAL(8,2)\\n- hazmat_routing BOOLEAN\\n- oversized_routing BOOLEAN\\n- avoid_tolls BOOLEAN\\n- avoid_highways BOOLEAN\\n- created_by VARCHAR(64)\\n- algorithm_version VARCHAR(16)\\n- _optimization_score FLOAT\\n- sys_created_on TIMESTAMP",
          "Traffic_Feed": "Columns:\\n- segment_id BIGINT (PK)\\n- source_vendor VARCHAR(32)\\n- observed_at TIMESTAMP\\n- jam_factor FLOAT\\n- speed_unconstrained FLOAT\\n- speed_current FLOAT\\n- travel_time_sec INT\\n- free_flow_time_sec INT\\n- closed_flag BOOLEAN\\n- construction_flag BOOLEAN\\n- incident_ref VARCHAR(32)\\n- event_description TEXT\\n- severity_level INT\\n- road_type VARCHAR(16)\\n- _provider_raw_json JSONB",
          "Toll_Rates": "Columns:\\n- toll_plaza_id VARCHAR(32) (PK)\\n- vehicle_class VARCHAR(16) (PK)\\n- time_of_day_category VARCHAR(16) (PK)\\n- currency VARCHAR(3)\\n- cost DECIMAL(10,2)\\n- transponder_discount DECIMAL(5,2)\\n- effective_date DATE\\n- expiry_date DATE\\n- active BOOLEAN\\n- plaza_name VARCHAR(128)\\n- operator_id VARCHAR(32)\\n- location GEOMETRY(Point, 4326)\\n- sys_updated_on TIMESTAMP",
          "Work_Order": "Columns:\\n- wo_number VARCHAR(32) (PK)\\n- wo_type VARCHAR(16)\\n- asset_id VARCHAR(36)\\n- parent_wo VARCHAR(32)\\n- requested_by VARCHAR(64)\\n- issue_description TEXT\\n- priority INT\\n- status VARCHAR(20)\\n- assigned_mechanic VARCHAR(64)\\n- scheduled_start TIMESTAMP\\n- scheduled_end TIMESTAMP\\n- actual_start TIMESTAMP\\n- actual_end TIMESTAMP\\n- downtime_hours DECIMAL(6,2)\\n- labor_hours DECIMAL(6,2)\\n- parts_cost DECIMAL(10,2)\\n- labor_cost DECIMAL(10,2)\\n- total_cost DECIMAL(10,2)\\n- resolution_code VARCHAR(16)\\n- resolution_notes TEXT\\n- warranty_claim BOOLEAN\\n- _cmms_sync_id VARCHAR(64)\\n- created_at TIMESTAMP\\n- updated_at TIMESTAMP",
          "Part_Inventory": "Columns:\\n- sku VARCHAR(64) (PK)\\n- warehouse_id VARCHAR(32) (PK)\\n- bin_location VARCHAR(32)\\n- item_description TEXT\\n- category_code VARCHAR(16)\\n- quantity_on_hand INT\\n- quantity_allocated INT\\n- quantity_in_transit INT\\n- reorder_level INT\\n- reorder_qty INT\\n- max_stock_level INT\\n- unit_of_measure VARCHAR(8)\\n- weight_kg DECIMAL(8,2)\\n- dimensions_cm JSONB\\n- hazardous_material BOOLEAN\\n- serial_number_tracked BOOLEAN\\n- lot_control_flag BOOLEAN\\n- supplier_id VARCHAR(36)\\n- unit_cost DECIMAL(10,2)\\n- currency VARCHAR(3)\\n- avg_lead_time_days INT\\n- last_cycle_count DATE\\n- abc_classification VARCHAR(1)\\n- _erp_sync_status VARCHAR(16)\\n- sys_updated_on TIMESTAMP",
          "Mechanic_Notes": "Columns:\\n- note_id UUID (PK)\\n- wo_reference VARCHAR(32)\\n- author_id VARCHAR(64)\\n- text_content TEXT\\n- note_type VARCHAR(16)\\n- is_internal BOOLEAN\\n- attachments JSONB\\n- dictation_audio_url VARCHAR(255)\\n- parsed_entities JSONB\\n- sentiment_score FLOAT\\n- created_at TIMESTAMP",
          "Bill_Of_Lading": "Columns:\\n- bol_number VARCHAR(32) (PK)\\n- sys_guid UUID\\n- shipper_id VARCHAR(36)\\n- shipper_address JSONB\\n- consignee_id VARCHAR(36)\\n- consignee_address JSONB\\n- bill_to_party VARCHAR(36)\\n- carrier_scac VARCHAR(4)\\n- equipment_initial VARCHAR(4)\\n- equipment_number VARCHAR(12)\\n- seal_number VARCHAR(32)\\n- freight_terms VARCHAR(16)\\n- declared_value DECIMAL(12,2)\\n- currency VARCHAR(3)\\n- total_weight_lbs DECIMAL(10,2)\\n- total_pallets INT\\n- hazmat_flag BOOLEAN\\n- un_number VARCHAR(4)\\n- temperature_control VARCHAR(32)\\n- special_instructions TEXT\\n- expected_delivery_date DATE\\n- pod_signature_url VARCHAR(255)\\n- edi_856_payload JSONB\\n- edi_204_payload JSONB\\n- source_erp VARCHAR(32)\\n- _created_by VARCHAR(64)\\n- _last_modified TIMESTAMP",
          "Customs_Declaration": "Columns:\\n- declaration_id VARCHAR(32) (PK)\\n- entry_number VARCHAR(32)\\n- filer_code VARCHAR(8)\\n- port_of_entry VARCHAR(8)\\n- port_of_unlading VARCHAR(8)\\n- transport_mode VARCHAR(16)\\n- carrier_code VARCHAR(8)\\n- vessel_flight_no VARCHAR(32)\\n- voyage_no VARCHAR(16)\\n- arrival_date DATE\\n- importer_of_record VARCHAR(32)\\n- ultimate_consignee VARCHAR(32)\\n- country_of_origin VARCHAR(2)\\n- export_country VARCHAR(2)\\n- harmonized_codes JSONB\\n- line_items_count INT\\n- total_value_usd DECIMAL(12,2)\\n- duties_usd DECIMAL(10,2)\\n- taxes_usd DECIMAL(10,2)\\n- fees_usd DECIMAL(10,2)\\n- clearance_status VARCHAR(16)\\n- release_date TIMESTAMP\\n- broker_ref VARCHAR(32)\\n- ace_response_message TEXT\\n- _edi_346_payload JSONB\\n- sys_updated_on TIMESTAMP",
          "Hazmat_Cert": "Columns:\\n- cert_id UUID (PK)\\n- un_number VARCHAR(4)\\n- packing_group VARCHAR(4)\\n- proper_shipping_name VARCHAR(128)\\n- hazard_class VARCHAR(8)\\n- subsidiary_risk VARCHAR(8)\\n- emergency_contact VARCHAR(32)\\n- erg_number INT\\n- marine_pollutant BOOLEAN\\n- poison_inhalation BOOLEAN\\n- flash_point_c DECIMAL(5,2)\\n- pdf_document_url VARCHAR(255)\\n- issued_by VARCHAR(64)\\n- expiry_date DATE\\n- verified_by VARCHAR(64)",
          "Temperature_Log": "Columns:\\n- log_id BIGINT (PK)\\n- reefer_id VARCHAR(32)\\n- container_id VARCHAR(32)\\n- temp_celsius DECIMAL(5,2)\\n- set_point DECIMAL(5,2)\\n- return_air_temp DECIMAL(5,2)\\n- supply_air_temp DECIMAL(5,2)\\n- ambient_temp DECIMAL(5,2)\\n- defrost_active BOOLEAN\\n- door_open BOOLEAN\\n- compressor_status VARCHAR(16)\\n- alarm_codes JSONB\\n- gps_location GEOMETRY(Point, 4326)\\n- recorded_at TIMESTAMP",
          "Deviation_Alert": "Columns:\\n- alert_id UUID (PK)\\n- alert_rule_id VARCHAR(32)\\n- entity_id VARCHAR(64)\\n- severity VARCHAR(16)\\n- metric_name VARCHAR(32)\\n- threshold_breach FLOAT\\n- current_value FLOAT\\n- duration_minutes INT\\n- alert_timestamp TIMESTAMP\\n- context_data JSONB\\n- acknowledged_by VARCHAR(64)\\n- acknowledged_at TIMESTAMP\\n- status VARCHAR(16)\\n- ticket_reference VARCHAR(32)\\n- _notification_sent BOOLEAN",
          "Audit_Trail": "Columns:\\n- audit_id BIGINT (PK)\\n- entity_type VARCHAR(32)\\n- entity_id VARCHAR(64)\\n- action VARCHAR(16)\\n- previous_state JSONB\\n- new_state JSONB\\n- changed_fields JSONB\\n- changed_by VARCHAR(64)\\n- user_ip VARCHAR(45)\\n- session_id VARCHAR(64)\\n- request_url VARCHAR(255)\\n- timestamp TIMESTAMP",
          "Model_Weights": "Columns:\\n- model_version VARCHAR(16) (PK)\\n- model_name VARCHAR(64)\\n- algorithm VARCHAR(32)\\n- binary_blob BYTEA\\n- hyperparameters JSONB\\n- features_used JSONB\\n- validation_rmse FLOAT\\n- validation_mae FLOAT\\n- training_duration_sec INT\\n- trained_by VARCHAR(64)\\n- deployed_at TIMESTAMP\\n- is_champion BOOLEAN\\n- artifact_uri VARCHAR(255)",
          "Feature_Vector": "Columns:\\n- vector_id UUID (PK)\\n- entity_id VARCHAR(64)\\n- entity_type VARCHAR(32)\\n- features FLOAT[]\\n- sparse_features JSONB\\n- schema_version VARCHAR(8)\\n- generated_at TIMESTAMP\\n- pipeline_run_id VARCHAR(64)\\n- is_imputed BOOLEAN\\n- _redis_cache_key VARCHAR(128)",
          "Inference_Result": "Columns:\\n- inference_id BIGINT (PK)\\n- model_version VARCHAR(16)\\n- entity_id VARCHAR(64)\\n- prediction_value FLOAT\\n- confidence_score FLOAT\\n- upper_bound FLOAT\\n- lower_bound FLOAT\\n- explainability_shap JSONB\\n- input_vector_id UUID\\n- executed_at TIMESTAMP\\n- latency_ms INT\\n- _consumed_by_downstream BOOLEAN",
          "Contract_Terms": "Columns:\\n- contract_id VARCHAR(32) (PK)\\n- supplier_id VARCHAR(36)\\n- buyer_id VARCHAR(36)\\n- status VARCHAR(16)\\n- effective_start DATE\\n- effective_end DATE\\n- sla_metrics JSONB\\n- penalty_clauses TEXT\\n- payment_terms VARCHAR(32)\\n- auto_renew BOOLEAN\\n- governing_law VARCHAR(64)\\n- signed_by VARCHAR(64)\\n- pdf_contract_url VARCHAR(255)\\n- _salesforce_id VARCHAR(18)\\n- sys_updated_on TIMESTAMP",
          "Performance_Metric": "Columns:\\n- metric_id UUID (PK)\\n- supplier_id VARCHAR(36)\\n- month_year VARCHAR(7)\\n- total_deliveries INT\\n- on_time_delivery_pct FLOAT\\n- in_full_delivery_pct FLOAT\\n- defect_rate_ppm INT\\n- average_delay_hrs DECIMAL(6,2)\\n- claims_filed INT\\n- total_claim_value DECIMAL(10,2)\\n- compliance_score FLOAT\\n- calculated_at TIMESTAMP\\n- is_finalized BOOLEAN",
          "Penalty_Log": "Columns:\\n- penalty_id BIGINT (PK)\\n- contract_id VARCHAR(32)\\n- supplier_id VARCHAR(36)\\n- incident_ref VARCHAR(64)\\n- violation_type VARCHAR(32)\\n- penalty_amount_usd DECIMAL(10,2)\\n- status VARCHAR(16)\\n- disputed BOOLEAN\\n- dispute_reason TEXT\\n- resolved_at TIMESTAMP\\n- applied_at TIMESTAMP\\n- invoice_deduction_ref VARCHAR(32)\\n- created_by VARCHAR(64)\\n- _erp_journal_id VARCHAR(32)"
        };"""

pattern = r"(const schemas3PL = \{[\s\S]*?\n        \};)"

if re.search(pattern, content):
    content = re.sub(pattern, new_schemas, content)
    with open(app_js_path, "w") as f:
        f.write(content)
    print("Replaced schemas successfully.")
else:
    print("Could not find schemas3PL dictionary.")
