#!/usr/bin/env node
/**
 * Generates the Runink web token layer from FACE's palette.
 *
 * Inputs (all committed, under tokens/):
 *   face-ramp.json  — vendored ARGB snapshot of FACE's two ramps, stamped with the
 *                     commit it was read from. face and site are separate repos, so
 *                     the site build must not need a sibling checkout.
 *   registry.json   — the web↔FACE mapping. The ONLY place the rename lives.
 *   derived.json    — web-only values, each with the measurement that justifies it.
 *
 * Outputs:
 *   ../../design-tokens.preset.js  — Tailwind preset, per-position palettes
 *   ../src/tokens.css              — the two grounds
 *   ../tokens/REGISTRY.md          — the human mapping table
 *
 * THE MECHANISM. FACE swaps two const ramps behind a getter, so ~580 call sites never
 * know which ramp they are on. A CSS custom property re-bound under a selector is that
 * same getter, which is why colour flows through `var()` rather than through `dark:`
 * variants — a missing `dark:` half renders plausibly wrong, and there is no compiler
 * on the web to catch it.
 *
 * WHY CHANNELS, NOT HEXES. Tailwind's alpha modifier (`bg-x/30`) needs an
 * `<alpha-value>` placeholder, and `withAlphaValue` cannot parse a bare `var(--x)`.
 * Emitting `rgb(var(--x-ch) / <alpha-value>)` over space-separated channels is what
 * keeps the 78 alpha-modified utilities in this package working. Get it wrong and
 * Tailwind DROPS those declarations silently — the design system still looks
 * plausible, and nothing in the validate/grade loop can see it. gen-tokens verifies
 * the count itself; see scripts/check-alpha-utilities.mjs.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '..');
const SITE = resolve(PKG, '../..');
const TOKENS = join(PKG, 'tokens');

const ramp = JSON.parse(readFileSync(join(TOKENS, 'face-ramp.json'), 'utf8'));
const registry = JSON.parse(readFileSync(join(TOKENS, 'registry.json'), 'utf8'));
const derived = JSON.parse(readFileSync(join(TOKENS, 'derived.json'), 'utf8'));

const GROUNDS = { console: 'console', sheet: 'sheet' };

/** '#AARRGGBB' → { r, g, b, a } with a in 0..1. */
function argb(hex) {
  const m = /^#([0-9A-Fa-f]{8})$/.exec(hex);
  if (!m) throw new Error(`expected #AARRGGBB, got ${hex}`);
  const n = m[1];
  return {
    a: parseInt(n.slice(0, 2), 16) / 255,
    r: parseInt(n.slice(2, 4), 16),
    g: parseInt(n.slice(4, 6), 16),
    b: parseInt(n.slice(6, 8), 16),
  };
}
const channels = (hex) => {
  const { r, g, b } = argb(hex);
  return `${r} ${g} ${b}`;
};

/** Every registry entry, flattened, in emission order. */
function allEntries() {
  const out = [];
  for (const group of ['surfaces', 'inks', 'fills', 'onFills']) {
    for (const e of registry[group] ?? []) out.push(e);
  }
  out.push(registry.severity.wash);
  for (const b of registry.severity.bands) out.push(b);
  return out;
}

/** Resolve one entry to its channel string for a given ground. */
function resolve1(entry, ground) {
  if (entry.const) return channels(entry.const);
  if (entry.face) {
    const table = ramp[ground];
    const v = table[entry.face];
    if (!v) throw new Error(`face token "${entry.face}" not in ramp.${ground}`);
    return channels(v);
  }
  return null; // derived — handled separately
}

/** textSecondary's alpha is baked and differs per ramp; edge is a derived alpha. */
function alphaFor(entry, ground) {
  if (entry.bakedAlpha && entry.face) return argb(ramp[ground][entry.face]).a;
  if (entry.web === 'edge') return derived.alpha.edge[ground];
  return null;
}

// ── tokens.css ────────────────────────────────────────────────────────────────
function emitCss() {
  const L = [];
  L.push('/**');
  L.push(' * GENERATED by scripts/gen-tokens.mjs — do not edit by hand.');
  L.push(' *');
  L.push(` * Runink's palette, from FACE ${ramp.provenance.commit.slice(0, 12)}.`);
  L.push(' * Source of truth: face/DESIGN.md §2 and flutter/lib/core/theme/runink_theme.dart.');
  L.push(' *');
  L.push(' * One identity, two grounds. `console` is the dark register and the default;');
  L.push(' * `sheet` is the light one. Set data-ground on any element to flip a subtree —');
  L.push(' * a console band inside a sheet page is a real requirement, which is why this is');
  L.push(' * a cascading attribute rather than a root-level dark: variant.');
  L.push(' *');
  L.push(' * The ground blocks contain ONLY channel assignments. That is deliberate: it makes');
  L.push(' * the two ramps trivially diffable and turns a token missing from one ramp into a');
  L.push(' * visible hole rather than a silently inherited wrong value.');
  L.push(' */');
  L.push('');

  // Layer 1 — primitives, keyed by the exact Dart field name.
  L.push('/* ── FACE primitives. Keyed by Dart field name; never used by a page. ── */');
  L.push(':root {');
  const faceNames = Object.keys(ramp.console).sort();
  for (const g of Object.keys(GROUNDS)) {
    for (const name of faceNames) {
      L.push(`  --rk-face-${name}-${g}: ${channels(ramp[g][name])};`);
    }
  }
  L.push('}');
  L.push('');

  // Layer 2 — semantics, per ground.
  const entries = allEntries();
  for (const [g, label] of Object.entries(GROUNDS)) {
    const sel = g === 'console' ? `:root,\n[data-ground='console']` : `[data-ground='sheet']`;
    L.push(`/* ── ${label} ── */`);
    L.push(`${sel} {`);
    L.push(`  color-scheme: ${g === 'console' ? 'dark' : 'light'};`);
    for (const e of entries) {
      if (e.web === 'edge') continue; // alpha-only, bound below
      const ch = resolve1(e, g);
      if (ch === null) continue;
      const via = e.face ? `var(--rk-face-${e.face}-${g})` : ch;
      L.push(`  --rk-${e.web}-ch: ${via};`);
      const a = alphaFor(e, g);
      if (a !== null) L.push(`  --rk-${e.web}-a: ${a};`);
    }
    // edge derives from the ink channel of this ground.
    L.push(`  --rk-edge-ch: var(--rk-primary-ch);`);
    L.push(`  --rk-edge-a: ${derived.alpha.edge[g]};`);
    L.push('}');
    L.push('');
  }

  // Layer 3 — derived forms that need no second ground block.
  L.push('/* ── Derived. rgb(var()) resolves where USED, so a subtree that rebinds a');
  L.push('   channel gets a correct wash for free — no color-mix, no re-derivation. ── */');
  L.push(':root {');
  for (const e of entries) {
    if (e.wash) L.push(`  --rk-${e.web}-wash: rgb(var(--rk-${e.web}-ch) / ${derived.alpha.wash.value});`);
  }
  L.push('}');
  L.push('');

  L.push('@media (prefers-reduced-motion: reduce) {');
  L.push('  *, *::before, *::after {');
  L.push('    animation-duration: 0.01ms !important;');
  L.push('    animation-iteration-count: 1 !important;');
  L.push('    transition-duration: 0.01ms !important;');
  L.push('  }');
  L.push('}');
  L.push('');
  return L.join('\n');
}

// ── preset ────────────────────────────────────────────────────────────────────
const POSITION_KEYS = [
  'backgroundColor',
  'textColor',
  'borderColor',
  'divideColor',
  'ringColor',
  'outlineColor',
  'fill',
  'stroke',
  'gradientColorStops',
  'boxShadowColor',
  'caretColor',
  'textDecorationColor',
];

function emitPreset() {
  const entries = allEntries();
  const palettes = Object.fromEntries(POSITION_KEYS.map((k) => [k, {}]));

  for (const e of entries) {
    const value =
      alphaFor(e, 'console') !== null && e.bakedAlpha
        ? `rgb(var(--rk-${e.web}-ch) / var(--rk-${e.web}-a))`
        : e.web === 'edge'
          ? `rgb(var(--rk-edge-ch) / var(--rk-edge-a))`
          : `rgb(var(--rk-${e.web}-ch) / <alpha-value>)`;
    for (const pos of e.positions) {
      if (!palettes[pos]) throw new Error(`registry: unknown position "${pos}" on ${e.web}`);
      palettes[pos][e.web] = value;
    }
    if (e.wash) {
      palettes.backgroundColor[`${e.web}-wash`] = `rgb(var(--rk-${e.web}-ch) / ${derived.alpha.wash.value})`;
    }
  }

  const body = {
    ...Object.fromEntries(POSITION_KEYS.filter((k) => Object.keys(palettes[k]).length).map((k) => [k, palettes[k]])),
    borderRadius: derived.borderRadius && Object.fromEntries(
      Object.entries(derived.borderRadius).filter(([k]) => !k.startsWith('$')),
    ),
    boxShadow: Object.fromEntries(Object.entries(derived.boxShadow).filter(([k]) => !k.startsWith('$'))),
    fontFamily: {
      sans: ['Figtree Rk', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
      display: ['Figtree Rk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
    },
    /*
     * cta-pulse referenced rgba(234,88,12,…) — the retired Saasify orange — baked
     * into the keyframe rather than into the colour map, which is exactly why it
     * would have survived a colour migration and pulsed a dead hue forever. It now
     * reads the accent channel, so it follows the active ground like everything else.
     */
    keyframes: {
      'cta-pulse': {
        '0%': { boxShadow: '0 0 0 0 rgb(var(--rk-fill-accent-ch) / 0.4)' },
        '70%': { boxShadow: '0 0 0 15px rgb(var(--rk-fill-accent-ch) / 0)' },
        '100%': { boxShadow: '0 0 0 0 rgb(var(--rk-fill-accent-ch) / 0)' },
      },
      marquee: {
        from: { transform: 'translateX(0)' },
        to: { transform: 'translateX(calc(-100% / 2))' },
      },
      'testimonials-scroll': {
        from: { transform: 'translateX(0)' },
        to: { transform: 'translateX(calc(-100% / 2))' },
      },
      'pulse-slow': {
        '0%, 100%': { opacity: '1' },
        '50%': { opacity: '0.4' },
      },
    },
    animation: {
      'cta-pulse': 'cta-pulse 2s infinite',
      marquee: 'marquee 40s infinite linear',
      'testimonials-scroll': 'testimonials-scroll 40s infinite linear',
      'pulse-slow': 'pulse-slow 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    },
  };

  const json = JSON.stringify(body, null, 2)
    .split('\n')
    .map((l, i) => (i === 0 ? l : '    ' + l))
    .join('\n');

  return `/**
 * GENERATED by packages/runink-ui/scripts/gen-tokens.mjs — do not edit by hand.
 * Edit tokens/registry.json (the mapping) or tokens/derived.json (web-only values)
 * and re-run \`npm run gen:tokens\` from packages/runink-ui.
 *
 * Runink's palette, from FACE ${ramp.provenance.commit.slice(0, 12)}.
 *
 * Colour palettes are defined PER POSITION rather than once under \`colors\`. That is
 * what makes fill-vs-ink structural instead of a convention: a fill token has no
 * textColor entry, so \`text-fill-success\` does not compile. FACE enforces the same
 * rule with a contrast test suite; here the utility simply does not exist.
 *
 * Values are rgb(var(--…-ch) / <alpha-value>) so Tailwind's /NN modifier keeps
 * working across both grounds. See tokens.css for why channels rather than hexes.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  theme: {
    extend: ${json},
  },
};
`;
}

// ── REGISTRY.md ───────────────────────────────────────────────────────────────
function emitRegistryMd() {
  const L = [];
  L.push('# Runink web tokens');
  L.push('');
  L.push('_Generated from `tokens/registry.json`. Do not edit._');
  L.push('');
  L.push(`Palette source: FACE \`${ramp.provenance.commit.slice(0, 12)}\` — \`${ramp.provenance.path}\`.`);
  L.push('');
  L.push('`tier` is the WCAG floor the token clears, and it decides which utilities exist:');
  L.push('a **fill** has no `text-*` utility at all, a **mark** clears 3:1 but not 4.5:1,');
  L.push('an **ink** clears 4.5:1 as text on all four surfaces of its ramp.');
  L.push('');
  L.push('| utility | FACE token | tier | console | sheet |');
  L.push('|---|---|---|---|---|');
  for (const e of allEntries()) {
    const face = e.face ?? e.faceConst ?? e.derived ?? '—';
    const c = e.const ?? (e.face ? ramp.console[e.face] : '—');
    const s = e.const ?? (e.face ? ramp.sheet[e.face] : '—');
    L.push(`| \`${e.web}\` | \`${face}\` | ${e.tier} | \`${c}\` | \`${s}\` |`);
  }
  L.push('');
  L.push('## Rules that are not negotiable');
  L.push('');
  L.push('- **Fills never carry text.** `fill-accent-deep`, `fill-success`, `fill-success-glow`,');
  L.push('  `fill-provenance` and `fill-severity` have no `text-*` utility by construction.');
  L.push('- **`ink-success` is the only olive that may carry text.**');
  L.push('- **`on-accent` inks `fill-accent` only** — it is not valid on `ink-accent`.');
  L.push('- **Severity is its own family.** Do not colour a status with accent/olive/wine.');
  L.push('  All five bands share one wash, and because adjacent bands cannot exceed ~1.17:1,');
  L.push('  every severity mark also carries a glyph or the word.');
  L.push('- **`hairline` is invisible on `surface-well`** (same value). Use `edge` there.');
  L.push('');
  return L.join('\n');
}

mkdirSync(join(PKG, 'src'), { recursive: true });
writeFileSync(join(PKG, 'src/tokens.css'), emitCss(), 'utf8');
writeFileSync(join(SITE, 'design-tokens.preset.js'), emitPreset(), 'utf8');
writeFileSync(join(TOKENS, 'REGISTRY.md'), emitRegistryMd(), 'utf8');

const entries = allEntries();
console.log(`wrote src/tokens.css, design-tokens.preset.js, tokens/REGISTRY.md`);
console.log(`  face commit : ${ramp.provenance.commit.slice(0, 12)}`);
console.log(`  tokens      : ${entries.length} (${entries.filter((e) => e.tier === 'fill').length} fill, ` +
  `${entries.filter((e) => e.tier === 'mark').length} mark, ${entries.filter((e) => e.tier === 'ink').length} ink)`);
console.log(`  washes      : ${entries.filter((e) => e.wash).length} at alpha ${derived.alpha.wash.value}`);
