name: Blog Request
description: Generate ROI-focused content for logistics and supply chain automation
title: "[Blog Request]: "
labels: ["blog-request"]
body:
  - type: markdown
    attributes:
      value: |
        Generate compelling blog articles that demonstrate **measurable business impact** and **ROI** for logistics and supply chain operations.

        **⏱️ Generation time:** 5-10 minutes | **💰 Potential reach:** C-suite decision makers

  - type: textarea
    id: context_links
    attributes:
      label: Context & Reference Links
      description: |
        Add any context, industry reports, or competitor links here to guide the AI:
      placeholder: |
        Industry Context: "Focus on the shift from manual audits to automated..."

        Reference Links:
        - https://example.com/report-2024
        - https://example.com/competitor-analysis
    validations:
      required: false

  - type: dropdown
    id: target_audience
    attributes:
      label: Target Decision Maker
      description: Who controls the budget for this initiative?
      options:
        - C-Suite Executives (CEO, CFO, COO)
        - VP of Operations / Supply Chain
        - VP of Technology / CTO
        - Directors of Logistics / Procurement
        - Finance & Business Operations Leaders
        - Mixed Audience (Technical + Business)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: content_focus
    attributes:
      label: Primary Value Driver
      description: What's the main "show me the money" angle?
      options:
        - Cost Reduction & Operational Efficiency
        - Revenue Growth & Market Expansion
        - Risk Mitigation & Compliance Savings
        - Speed to Market & Competitive Advantage
        - Customer Satisfaction & Retention ROI
        - Balanced (Multiple Value Drivers)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### ⚙️ What Happens Next?

        1. **AI Research**: The system pulls industry data, case studies, and ROI benchmarks
        2. **Value-Focused Writing**: Generates executive-ready content with clear financial impact
        3. **Review**: Article delivered for approval with embedded metrics and sources
        4. **Publish**: Goes live to attract high-intent, budget-holding decision makers

        **Questions?** Check our [documentation](../cmd/DOCKER.md) or reach out to the team.
